### ISSUE TITLE
Android Firefox version must be quite modern

### ISSUE THREAD

**Issue by Brod8362** [Rob--W/firefox-android-backup-restore#1]
This isn't an actual issue, but I wanted to document this in case someone else has the same problem.

If you try running this on slightly older versions of Firefox (I was trying 113), you might face a message like this: 

`Failed to load resource://gre/modules/ctypes.sys.mjs`

For me, updating to the latest version of Firefox mobile (123.0 at time of writing) fixed the issue.

**Comment by Brod8362** [comment]
Closing because as mentioned above, this is just for documentation's sake. Also THANK YOU @Rob--W for making this, I have been looking for an offline Firefox mobile backup tool for a long time.

**Comment by Rob--W** [comment]
ctypes.sys.mjs was called ctypes.jsm in older Firefox versions (113 and older).

To update the script for older versions, change:
https://github.com/Rob--W/firefox-android-backup-restore/blob/14bd61a246247b73c3b81f882310b9bda8e33d0a/snippets_for_firefox_debugging.js#L141-L142

- use ctypes.jsm instead of ctypes.sys.mjs
- use `ChromeUtils.import` instead of `ChromeUtils.importESModule`

 ... but updating to a recent Firefox version would work too, and is actually recommended. Web browsers should generally be on a recent version when possible.

**Comment by Brod8362** [comment]
Thanks for the feedback. This device has been signed out of Google play for a long time (hence the old FF version), but updating w/ Aurora store worked fine. So even if a device is not signed into google play, it should still be possible to update & run the script unmodified.

**Comment by Efreak** [comment]
This is still useful information as I had been keeping Mull around on an unrooted device specifically because there was a large amount (10gb+) of unexportable indexeddb data in a couple of web apps I use. Fortunately, this solution works fine for moving data *across versions* of Firefox-based browsers. Mull was transferred successfully to Firefox beta, Firefox stable successfully transferred to Firefox stable. Firefox nightly, where I had the most data, unfortunately *did not* (the transfer worked without errors, and the browser itself works, but loading websites crashes it[^1]; I intend to try and wipe most of the backed up data, as the indexeddb and local storage are all I need). Now if only I had a solution for chrome...

[^1]: Edit: it appears to be passwords that are crashing nightly
